import type { RequestDetail as Detail } from '@/lib/api';
import type { RequestDraft } from '@/shared/types';

/** Rebuilds an editable draft from a stored request, for "Edit & resubmit". */
export function toDraft(r: Detail['request']): RequestDraft {
  return {
    requestId: r.requestId,
    scope: r.scope,
    city: r.city,
    claimType: r.claimType,
    travelType: r.travelType,
    teamMembers: r.teamMembers,
    fromDate: r.fromDate,
    toDate: r.toDate,
    purpose: r.purpose,
    destinationType: r.destinationType,
    tripDirection: r.tripDirection,
    route: r.route,
    dhakaOffice: r.dhakaOffice,
    exceptionClaimed: r.exceptionClaimed,
    exceptionReason: r.exceptionReason,
    advanceWanted: r.advanceWanted,
    payoutMethod: r.payoutMethod,
    bankName: r.bankName,
    bankAccountName: r.bankAccountName,
    bankAccountNumber: r.bankAccountNumber,
    bankRoutingNumber: r.bankRoutingNumber,
    bankBranch: r.bankBranch,
    destination: r.destination,
    startTime: r.startTime,
    endTime: r.endTime,
    workedAt: r.workedAt,
    arrangement: r.arrangement,
    transportMode: r.transportMode,
    vehicleType: r.vehicleType,
    carSpecialApproval: r.carSpecialApproval,
    travelFrom: r.travelFrom,
    travelTo: r.travelTo,
    totalKM: r.totalKM,
    legs: r.legs,
    officeMealTaken: r.officeMealTaken,
    dualWorkstation: r.dualWorkstation,
    dualWorkstationType: r.dualWorkstationType,
    accommodationType: r.accommodationType,
    hotelName: r.hotelName,
    checkIn: r.checkIn,
    checkOut: r.checkOut,
    accommodationAmount: r.accommodationAmount,
    rentACarAmount: r.rentACarAmount,
    rentACarHeadcount: r.rentACarHeadcount,
    flightAmount: r.flightAmount,
    otherAmount: r.otherAmount,
    otherNote: r.otherNote,
    advanceType: r.advanceType,
    advanceRequested: r.advanceRequested,
    bkashNumber: r.bkashNumber,
    documentTypes: r.documentTypes,
    documentLinks: r.documentLinks,
    employeeNote: r.employeeNote,
  };
}
